import "dotenv/config";
import pg from "pg";
import { PrismaClient } from "../../generated/prisma/index.js";
import { PrismaPg } from "@prisma/adapter-pg";

const { Pool } = pg;
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function seedAssetCodes() {
  const assetCodes = [
    { code: "XAG", name: "Silver", unit: "Troy Ounce" },
    { code: "XAG-BID", name: "Silver Bid", unit: "Troy Ounce" },
    { code: "XAG-ASK", name: "Silver Ask", unit: "Troy Ounce" },
    { code: "XAU", name: "Gold", unit: "Troy Ounce" },
    { code: "XAU-BID", name: "Gold Bid", unit: "Troy Ounce" },
    { code: "XAU-ASK", name: "Gold Ask", unit: "Troy Ounce" },
    { code: "XPD", name: "Palladium", unit: "Troy Ounce" },
    { code: "XPD-BID", name: "Palladium Bid", unit: "Troy Ounce" },
    { code: "XPD-ASK", name: "Palladium Ask", unit: "Troy Ounce" },
    { code: "XPT", name: "Platinum", unit: "Troy Ounce" },
    { code: "XPT-BID", name: "Platinum Bid", unit: "Troy Ounce" },
    { code: "XPT-ASK", name: "Platinum Ask", unit: "Troy Ounce" },
    { code: "XRH", name: "Rhodium", unit: "Ounce" },
    { code: "ALU", name: "Aluminum", unit: "Ounce" },
    { code: "XCO", name: "Cobalt", unit: "Ounce" },
    { code: "XCU", name: "Copper", unit: "Ounce" },
    { code: "XGA", name: "Gallium", unit: "Ounce" },
    { code: "XIN", name: "Indium", unit: "Ounce" },
    { code: "IRON", name: "Iron Ore", unit: "Ounce" },
    { code: "XPB", name: "Lead", unit: "Ounce" },
    { code: "XLI", name: "Lithium", unit: "Ounce" },
    { code: "XMO", name: "Molybdenum", unit: "Ounce" },
    { code: "NI", name: "Nickel", unit: "Ounce" },
    { code: "XND", name: "Neodymium", unit: "Ounce" },
    { code: "XSN", name: "Tin", unit: "Ounce" },
    { code: "XTE", name: "Tellurium", unit: "Ounce" },
    { code: "XU", name: "Uranium", unit: "Ounce" },
    { code: "ZNC", name: "Zinc", unit: "Ounce" },
    { code: "XAU-AHME", name: "Ahmedabad Gold", unit: "Troy Ounce" },
    { code: "XAU-BANG", name: "Bangalore Gold", unit: "Troy Ounce" },
    { code: "XAU-BHOP", name: "Bhopal Gold", unit: "Troy Ounce" },
    { code: "XAU-CHAN", name: "Chandigarh Gold", unit: "Troy Ounce" },
    { code: "XAU-CHEN", name: "Chennai Gold", unit: "Troy Ounce" },
    { code: "XAU-COIM", name: "Coimbatore Gold", unit: "Troy Ounce" },
    { code: "XAU-DEHR", name: "Dehradun Gold", unit: "Troy Ounce" },
    { code: "XAU-FARI", name: "Faridabad Gold", unit: "Troy Ounce" },
    { code: "XAU-GURG", name: "Gurgaon Gold", unit: "Troy Ounce" },
    { code: "XAU-GUWA", name: "Guwahati Gold", unit: "Troy Ounce" },
    { code: "XAU-HYDE", name: "Hyderabad Gold", unit: "Troy Ounce" },
    { code: "XAU-INDO", name: "Indore Gold", unit: "Troy Ounce" },
    { code: "XAU-JAIP", name: "Jaipur Gold", unit: "Troy Ounce" },
    { code: "XAU-KANP", name: "Kanpur Gold", unit: "Troy Ounce" },
    { code: "XAU-KOCH", name: "Kochi Gold", unit: "Troy Ounce" },
    { code: "XAU-KOLH", name: "Kolhapur Gold", unit: "Troy Ounce" },
    { code: "XAU-KOLK", name: "Kolkata Gold", unit: "Troy Ounce" },
    { code: "XAU-LUCK", name: "Lucknow Gold", unit: "Troy Ounce" },
    { code: "XAU-LUDH", name: "Ludhiana Gold", unit: "Troy Ounce" },
    { code: "XAU-MADU", name: "Madurai Gold", unit: "Troy Ounce" },
    { code: "XAU-MALA", name: "Malappuram Gold", unit: "Troy Ounce" },
    { code: "XAU-MANG", name: "Mangalore Gold", unit: "Troy Ounce" },
    { code: "XAU-MEER", name: "Meerut Gold", unit: "Troy Ounce" },
    { code: "XAU-MUMB", name: "Mumbai Gold", unit: "Troy Ounce" },
    { code: "XAU-MYSO", name: "Mysore Gold", unit: "Troy Ounce" },
    { code: "XAU-NAGP", name: "Nagpur Gold", unit: "Troy Ounce" },
    { code: "XAU-NOID", name: "Noida Gold", unit: "Troy Ounce" },
    { code: "XAU-PATN", name: "Patna Gold", unit: "Troy Ounce" },
    { code: "XAU-POND", name: "Pondicherry Gold", unit: "Troy Ounce" },
    { code: "XAU-PUNE", name: "Pune Gold", unit: "Troy Ounce" },
    { code: "XAU-RAIP", name: "Raipur Gold", unit: "Troy Ounce" },
    { code: "XAU-SALE", name: "Salem Gold", unit: "Troy Ounce" },
    { code: "XAU-VIJA", name: "Vijayawada Gold", unit: "Troy Ounce" },
    { code: "XAU-VISA", name: "Visakhapatnam Gold", unit: "Troy Ounce" },
    { code: "XAG-AHME", name: "Ahmedabad Silver", unit: "Troy Ounce" },
    { code: "XAG-BANG", name: "Bangalore Silver", unit: "Troy Ounce" },
    { code: "XAG-CHAN", name: "Chandigarh Silver", unit: "Troy Ounce" },
    { code: "XAG-CHEN", name: "Chennai Silver", unit: "Troy Ounce" },
    { code: "XAG-COIM", name: "Coimbatore Silver", unit: "Troy Ounce" },
    { code: "XAG-HYDE", name: "Hyderabad Silver", unit: "Troy Ounce" },
    { code: "XAG-JAIP", name: "Jaipur Silver", unit: "Troy Ounce" },
    { code: "XAG-KOLK", name: "Kolkata Silver", unit: "Troy Ounce" },
    { code: "XAG-LUCK", name: "Lucknow Silver", unit: "Troy Ounce" },
    { code: "XAG-MADU", name: "Madurai Silver", unit: "Troy Ounce" },
    { code: "XAG-MANG", name: "Mangalore Silver", unit: "Troy Ounce" },
    { code: "XAG-MUMB", name: "Mumbai Silver", unit: "Troy Ounce" },
    { code: "XAG-MYSO", name: "Mysore Silver", unit: "Troy Ounce" },
    { code: "XAG-NAGP", name: "Nagpur Silver", unit: "Troy Ounce" },
    { code: "XAG-PATN", name: "Patna Silver", unit: "Troy Ounce" },
    { code: "XAG-PUNE", name: "Pune Silver", unit: "Troy Ounce" },
    { code: "XAG-SALE", name: "Salem Silver", unit: "Troy Ounce" },
    { code: "XAG-VIJA", name: "Vijayawada Silver", unit: "Troy Ounce" },
    { code: "ADA", name: "Cardano", unit: null },
    { code: "BNB", name: "Binance Coin", unit: null },
    { code: "BTC", name: "Bitcoin", unit: null },
    { code: "DOGE", name: "Dogecoin", unit: null },
    { code: "DOT", name: "Polkadot", unit: null },
    { code: "ETH", name: "Ethereum", unit: null },
    { code: "LINK", name: "Chainlink", unit: null },
    { code: "LTC", name: "Litecoin", unit: null },
    { code: "SOL", name: "Solana", unit: null },
    { code: "TRX", name: "Tron", unit: null },
    { code: "USDC", name: "USD Coin", unit: null },
    { code: "USDT", name: "Tether", unit: null },
    { code: "XRP", name: "Ripple", unit: null },
    { code: "BRENT", name: "Brent Crude", unit: "per Barrel (Bbl)" },
    { code: "GASOLINE", name: "Gasoline", unit: "per Gallon (Gal)" },
    {
      code: "NATURALGAS",
      name: "Natural Gas",
      unit: "per Million British Thermal Units (MMBtu)",
    },
    { code: "WTI", name: "West Texas Intermediate", unit: "per Barrel (Bbl)" },
    { code: "AED", name: "UAE Dirham", unit: null },
    { code: "AFN", name: "Afghan Afghani", unit: null },
    { code: "ALL", name: "Albanian Lek", unit: null },
    { code: "AMD", name: "Armenian Dram", unit: null },
    { code: "ANG", name: "Netherlands Antillean Guilder", unit: null },
    { code: "AOA", name: "Angolan Kwanza", unit: null },
    { code: "ARS", name: "Argentine Peso", unit: null },
    { code: "AUD", name: "Australian Dollar", unit: null },
    { code: "AZN", name: "Azerbaijan Manat", unit: null },
    {
      code: "BAM",
      name: "Bosnia And Herzegovina Convertible Mark",
      unit: null,
    },
    { code: "BBD", name: "Barbadian Dollar", unit: null },
    { code: "BDT", name: "Bangladeshi Taka", unit: null },
    { code: "BGN", name: "Bulgarian Lev", unit: null },
    { code: "BHD", name: "Bahraini Dinar", unit: null },
    { code: "BIF", name: "Burundi Franc", unit: null },
    { code: "BIH", name: "Bosnia-Herzegovina Convertible Mark", unit: null },
    { code: "BND", name: "Brunei Dollar", unit: null },
    { code: "BOB", name: "Bolivian Boliviano", unit: null },
    { code: "BRL", name: "Brazilian Real", unit: null },
    { code: "BSD", name: "Bahamian Dollar", unit: null },
    { code: "BTN", name: "Bhutanese Ngultrum", unit: null },
    { code: "BWP", name: "Botswanan Pula", unit: null },
    { code: "BYN", name: "Belarusian Ruble", unit: null },
    { code: "BZD", name: "Belize Dollar", unit: null },
    { code: "CAD", name: "Canadian Dollar", unit: null },
    { code: "CDF", name: "Congolese Franc", unit: null },
    { code: "CHF", name: "Swiss Franc", unit: null },
    { code: "CLF", name: "Chilean Unit Of Account", unit: null },
    { code: "CLP", name: "Chilean Peso", unit: null },
    { code: "CNY", name: "Chinese Yuan Renminbi", unit: null },
    { code: "COP", name: "Colombian Peso", unit: null },
    { code: "CRC", name: "Costa Rican Colon", unit: null },
    { code: "CVE", name: "Cape Verdean Escudo", unit: null },
    { code: "CZK", name: "Czech Koruna", unit: null },
    { code: "DJF", name: "Djiboutian Franc", unit: null },
    { code: "DKK", name: "Danish Krone", unit: null },
    { code: "DOP", name: "Dominican Peso", unit: null },
    { code: "DZD", name: "Algerian Dinar", unit: null },
    { code: "EGP", name: "Egyptian Pound", unit: null },
    { code: "ERN", name: "Eritrean Nakfa", unit: null },
    { code: "ETB", name: "Ethiopian Birr", unit: null },
    { code: "EUR", name: "European Euro", unit: null },
    { code: "FJD", name: "Fijian Dollar", unit: null },
    { code: "FKP", name: "Falkland Islands Pound", unit: null },
    { code: "GBP", name: "Pound Sterling", unit: null },
    { code: "GEL", name: "Georgian Lari", unit: null },
    { code: "GHS", name: "Ghanaian Cedi", unit: null },
    { code: "GIP", name: "Gibraltar Pound", unit: null },
    { code: "GMD", name: "Gambian Dalasi", unit: null },
    { code: "GNF", name: "Guinean Franc", unit: null },
    { code: "GTQ", name: "Guatemalan Quetzal", unit: null },
    { code: "GYD", name: "Guyanese Dollar", unit: null },
    { code: "HKD", name: "Hong Kong Dollar", unit: null },
    { code: "HNL", name: "Honduran Lempira", unit: null },
    { code: "HRK", name: "Croatian Kuna", unit: null },
    { code: "HTG", name: "Haitian Gourde", unit: null },
    { code: "HUF", name: "Hungarian Forint", unit: null },
    { code: "IDR", name: "Indonesian Rupiah", unit: null },
    { code: "ILS", name: "Israeli New Shekel", unit: null },
    { code: "INR", name: "Indian Rupee", unit: null },
    { code: "IQD", name: "Iraqi Dinar", unit: null },
    { code: "IRR", name: "Iranian Rial", unit: null },
    { code: "ISK", name: "Icelandic Krona", unit: null },
    { code: "JMD", name: "Jamaican Dollar", unit: null },
    { code: "JOD", name: "Jordanian Dinar", unit: null },
    { code: "JPY", name: "Japanese Yen", unit: null },
    { code: "KES", name: "Kenyan Shilling", unit: null },
    { code: "KGS", name: "Kyrgyzstani Som", unit: null },
    { code: "KHR", name: "Cambodian Riel", unit: null },
    { code: "KMF", name: "Comorian Franc", unit: null },
    { code: "KRW", name: "South Korean Won", unit: null },
    { code: "KWD", name: "Kuwaiti Dinar", unit: null },
    { code: "KYD", name: "Cayman Islands Dollar", unit: null },
    { code: "KZT", name: "Kazakhstani Tenge", unit: null },
    { code: "LAK", name: "Lao Kip", unit: null },
    { code: "LBP", name: "Lebanese Pound", unit: null },
    { code: "LKR", name: "Sri Lankan Rupee", unit: null },
    { code: "LRD", name: "Liberian Dollar", unit: null },
    { code: "LSL", name: "Lesotho Loti", unit: null },
    { code: "LYD", name: "Libyan Dinar", unit: null },
    { code: "MAD", name: "Moroccan Dirham", unit: null },
    { code: "MDL", name: "Moldovan Leu", unit: null },
    { code: "MGA", name: "Malagasy Ariary", unit: null },
    { code: "MKD", name: "Macedonian Denar", unit: null },
    { code: "MMK", name: "Myanmar Kyat", unit: null },
    { code: "MNT", name: "Mongolian Tugrik", unit: null },
    { code: "MOP", name: "Macanese Pataca", unit: null },
    { code: "MRO", name: "Mauritanian Ouguiya", unit: null },
    { code: "MUR", name: "Mauritian Rupee", unit: null },
    { code: "MVR", name: "Maldivian Rufiyaa", unit: null },
    { code: "MWK", name: "Malawian Kwacha", unit: null },
    { code: "MXN", name: "Mexican Peso", unit: null },
    { code: "MYR", name: "Malaysian Ringgit", unit: null },
    { code: "MZN", name: "Mozambican Metical", unit: null },
    { code: "NAD", name: "Namibian Dollar", unit: null },
    { code: "NGN", name: "Nigerian Naira", unit: null },
    { code: "NIO", name: "Nicaraguan Cordoba", unit: null },
    { code: "NOK", name: "Norwegian Krone", unit: null },
    { code: "NPR", name: "Nepalese Rupee", unit: null },
    { code: "NZD", name: "New Zealand Dollar", unit: null },
    { code: "OMR", name: "Omani Rial", unit: null },
    { code: "PAB", name: "Panamanian Balboa", unit: null },
    { code: "PEN", name: "Peruvian Sol", unit: null },
    { code: "PHP", name: "Philippine Peso", unit: null },
    { code: "PKR", name: "Pakistani Rupee", unit: null },
    { code: "PLN", name: "Polish Zloty", unit: null },
    { code: "PYG", name: "Paraguayan Guarani", unit: null },
    { code: "QAR", name: "Qatari Riyal", unit: null },
    { code: "RON", name: "Romanian Leu", unit: null },
    { code: "RSD", name: "Serbian Dinar", unit: null },
    { code: "RUB", name: "Russian Ruble", unit: null },
    { code: "RWF", name: "Rwandan Franc", unit: null },
    { code: "SAR", name: "Saudi Arabian Riyal", unit: null },
    { code: "SCR", name: "Seychellois Rupee", unit: null },
    { code: "SDG", name: "Sudanese Pound", unit: null },
    { code: "SEK", name: "Swedish Krona", unit: null },
    { code: "SGD", name: "Singapore Dollar", unit: null },
    { code: "SHP", name: "Saint Helena Pound", unit: null },
    { code: "SLL", name: "Sierra Leonean Leone", unit: null },
    { code: "SOS", name: "Somali Shilling", unit: null },
    { code: "SRD", name: "Surinamese Dollar", unit: null },
    { code: "STN", name: "Sao Tome And Principe Dobra", unit: null },
    { code: "SYP", name: "Syrian Pound", unit: null },
    { code: "SVC", name: "Salvadoran Colón", unit: null },
    { code: "SZL", name: "Swazi Lilangeni", unit: null },
    { code: "THB", name: "Thai Baht", unit: null },
    { code: "TJS", name: "Tajikistani Somoni", unit: null },
    { code: "TMT", name: "Turkmen Manat", unit: null },
    { code: "TND", name: "Tunisian Dinar", unit: null },
    { code: "TOP", name: "Tongan Pa'anga", unit: null },
    { code: "TRY", name: "Turkish Lira", unit: null },
    { code: "TTD", name: "Trinidad And Tobago Dollar", unit: null },
    { code: "TWD", name: "New Taiwan Dollar", unit: null },
    { code: "TZS", name: "Tanzanian Shilling", unit: null },
    { code: "UAH", name: "Ukrainian Hryvnia", unit: null },
    { code: "UGX", name: "Ugandan Shilling", unit: null },
    { code: "USD", name: "United States Dollar", unit: null },
    { code: "UYU", name: "Uruguayan Peso", unit: null },
    { code: "UZS", name: "Uzbekistani Som", unit: null },
    { code: "VES", name: "Venezuelan Bolivar", unit: null },
    { code: "VND", name: "Vietnamese Dong", unit: null },
    { code: "VUV", name: "Vanuatu Vatu", unit: null },
    { code: "WST", name: "Samoan Tala", unit: null },
    { code: "XAF", name: "Central African CFA Franc", unit: null },
    { code: "XCD", name: "East Caribbean Dollar", unit: null },
    { code: "XOF", name: "West African CFA Franc", unit: null },
    { code: "XPF", name: "CFP Franc", unit: null },
    { code: "YER", name: "Yemeni Rial", unit: null },
    { code: "ZAR", name: "South African Rand", unit: null },
    { code: "ZMK", name: "Zambian Kwacha (pre-2013)", unit: null },
    { code: "ZMW", name: "Zambian Kwacha", unit: null },
  ];

  console.log("Starting to seed AssetCode data...");
  let count = 0;

  for (const asset of assetCodes) {
    try {
      await prisma.assetCode.upsert({
        where: { code: asset.code },
        update: {
          name: asset.name,
          unit: asset.unit,
        },
        create: {
          code: asset.code,
          name: asset.name,
          unit: asset.unit,
        },
      });
      count++;
      console.log(`✓ Imported: ${asset.code} - ${asset.name}`);
    } catch (error) {
      console.error(`✗ Failed to import: ${asset.code}`, error.message);
    }
  }

  console.log(`\nSuccessfully imported ${count} asset codes`);
}

async function main() {
  // Seed AssetCode data
  await seedAssetCodes();
}
main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
